# Generated by Django 3.1.2 on 2020-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apuntes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='documento',
            field=models.FileField(upload_to='apuntes/docu/img'),
        ),
    ]
