# Generated by Django 3.1.2 on 2020-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apuntes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apunte',
            name='tamaño',
        ),
        migrations.AlterField(
            model_name='apunte',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='paginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='tipo',
            field=models.CharField(default='unknown', max_length=80),
        ),
    ]
