# Generated by Django 3.1.2 on 2020-12-09 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apuntes', '0002_auto_20201207_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='editado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
