# Generated by Django 3.1.2 on 2020-11-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apuntes', '0002_auto_20201124_1705'),
        ('Apuntes', '0002_auto_20201124_1245'),
    ]

    operations = [
    ]
