# Generated by Django 3.1.2 on 2020-11-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apuntes', '0003_merge_20201128_1653'),
        ('Apuntes', '0004_merge_20201128_2230'),
    ]

    operations = [
    ]
