# Generated by Django 3.1.2 on 2020-11-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apuntes', '0003_merge_20201128_1653'),
        ('Apuntes', '0005_merge_20201129_1230'),
    ]

    operations = [
    ]
