# Generated by Django 3.1.2 on 2020-11-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
