# Generated by Django 3.1.2 on 2020-11-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0002_auto_20201113_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textquestion',
            old_name='text_answer',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Trivia.question'),
        ),
    ]
