# Generated by Django 3.1.2 on 2020-11-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0003_auto_20201117_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='question_type',
            field=models.CharField(choices=[('multichoice', 'Multichoice Question'), ('text', 'Text')], default='text', max_length=25),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multichoice', 'Multichoice Question'), ('text', 'Text')], default='text', max_length=25),
        ),
    ]
