# Generated by Django 3.1.2 on 2020-12-08 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblio', '0004_auto_20201204_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('book_add', 'Book Added'), ('book_rate', 'Book Rated'), ('book_page_change', 'Book Page Changed'), ('post_add', 'Post Added'), ('post_comment', 'Post Commented'), ('post_like', 'Post liked'), ('apunte_add', 'Apunte added')], default='private', max_length=35)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionBookRate',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.action')),
                ('valoracion', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('Blog.action',),
        ),
        migrations.CreateModel(
            name='ActionBookPageChange',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.action')),
                ('page', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('Blog.action',),
        ),
        migrations.CreateModel(
            name='ActionBookAdd',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.action')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('Blog.action',),
        ),
    ]
