# Generated by Django 3.1.2 on 2020-12-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action',
        ),
    ]
