# Generated by Django 3.1.2 on 2020-12-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
        ('Biblio', '0004_auto_20201204_1147'),
        ('Blog', '0002_remove_action_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPostLike',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.action')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.post')),
            ],
            bases=('Blog.action',),
        ),
        migrations.CreateModel(
            name='ActionPostComment',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.action')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.post')),
            ],
            bases=('Blog.action',),
        ),
        migrations.CreateModel(
            name='ActionPostAdd',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.action')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.post')),
            ],
            bases=('Blog.action',),
        ),
        migrations.CreateModel(
            name='ActionApunteAdd',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.action')),
                ('apunte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('Blog.action',),
        ),
    ]
