# Generated by Django 3.1.2 on 2020-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_content_editor',
            field=models.BooleanField(default=False),
        ),
    ]
