# Generated by Django 3.1.2 on 2020-12-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_is_content_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_t11',
            field=models.ImageField(blank=True, null=True, upload_to='model/img/users_t11/'),
        ),
    ]
