# Generated by Django 3.1.2 on 2020-11-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userfollowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_counter', models.IntegerField(default=0)),
                ('view_counter', models.IntegerField(default=0)),
                ('book_upload_counter', models.IntegerField(default=0)),
                ('book_readed_counter', models.IntegerField(default=0)),
                ('following_counter', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
