# Generated by Django 3.1.4 on 2021-06-04 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Biblio', '0001_initial'),
        ('Forum', '0002_auto_20201213_1444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('public', 'Public')], default='public', max_length=35)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPostLike',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.post')),
            ],
            bases=('UserMechanics.action',),
        ),
        migrations.CreateModel(
            name='ActionPostComment',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.post')),
            ],
            bases=('UserMechanics.action',),
        ),
        migrations.CreateModel(
            name='ActionPostAdd',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.post')),
            ],
            bases=('UserMechanics.action',),
        ),
        migrations.CreateModel(
            name='ActionBookState',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('UserMechanics.action',),
        ),
        migrations.CreateModel(
            name='ActionBookRate',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('valoracion', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('UserMechanics.action',),
        ),
        migrations.CreateModel(
            name='ActionBookPageChange',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('page', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('UserMechanics.action',),
        ),
        migrations.CreateModel(
            name='ActionBookAdd',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('UserMechanics.action',),
        ),
    ]
