# Generated by Django 3.1.4 on 2020-12-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0005_book_cover_t36'),
        ('Apuntes', '0003_auto_20201209_2058'),
        ('UserMechanics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionapunteadd',
            name='apunte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apuntes.apunte'),
        ),
        migrations.CreateModel(
            name='ActionBookState',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserMechanics.action')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
            ],
            bases=('UserMechanics.action',),
        ),
    ]
