# Generated by Django 3.1.4 on 2020-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMechanics', '0002_auto_20201210_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('public', 'Public')], default='public', max_length=35),
        ),
    ]
