# Generated by Django 3.1.2 on 2020-11-29 11:30

import apps.Biblio.external
import apps.Biblio.models
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('npages', models.IntegerField()),
                ('book_file', models.FileField(blank=True, default=None, null=True, upload_to='biblio/books/docs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='biblio/books/covers/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from=apps.Biblio.models.custom_populate, unique_with=('title', 'author'))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('public', 'Public')], default='private', max_length=35)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='Biblio.author')),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='BookUserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', apps.Biblio.external.IntegerRangeField(blank=True, null=True)),
                ('book_state', models.CharField(choices=[('want_to_read', 'Want to Read'), ('reading', 'Reading'), ('read', 'Read'), ('dropped', 'Dropped'), ('on_hold', 'On Hold')], default='want_to_read', max_length=30)),
                ('act_page', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblio.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='users', through='Biblio.BookUserDetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
