# Generated by Django 3.1.2 on 2020-12-02 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='added_books', through='Biblio.BookUserDetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
