# Generated by Django 3.1.2 on 2020-11-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0002_auto_20201128_1402'),
        ('Biblio', '0002_auto_20201128_0044'),
    ]

    operations = [
    ]
