# Generated by Django 3.1.2 on 2020-12-02 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblio', '0002_auto_20201202_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
