# Generated by Django 3.1.2 on 2020-12-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0003_auto_20201202_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserdetail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_details', to='Biblio.book'),
        ),
    ]
