# Generated by Django 3.1.2 on 2020-12-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0004_auto_20201204_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_t36',
            field=models.ImageField(blank=True, null=True, upload_to='biblio/books/covers_t36/'),
        ),
    ]
