# Generated by Django 3.1.2 on 2020-11-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20201129_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
