# Generated by Django 3.1.2 on 2020-11-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20201128_1653'),
        ('Forum', '0003_auto_20201128_1409'),
        ('Forum', '0003_auto_20201128_0044'),
    ]

    operations = [
    ]
