# Generated by Django 3.1.2 on 2020-11-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0006_auto_20201129_1232'),
        ('Forum', '0004_merge_20201129_1058'),
    ]

    operations = [
    ]
